Automate certificate installation via the cPanel UAPI
letsdebug/certbot-cpanel-dns-auth-hook pull request #4
Opened 2022-10-03 21:41 UTC by DragoonAethis

This PR adds an extra feature that's not used by Certbot directly, but allows optional automatic installation of the generated certificate. It uses mostly the same configuration/env vars to call the cPanel `SSL/install_ssl` UAPI with the specified domain and the current live certificate.

The README is updated with the additional config vars (which are optional and used for installation only). To test this, add the new config vars and run `./cpanel-dns.py install` - the script will print the server's summary, which usually is something like `['The certificate was successfully installed on the domain “example.com”.']`.

Of course, if you'd prefer not to carry this patch, let me know and I'll close this PR - it's technically not something that Certbot can use directly, just a convenient extra.

2022-10-03 22:22 UTC, alexzorin reviewed
Thanks!

>Of course, if you'd prefer not to carry this patch, let me know and I'll close this PR - it's technically not something that Certbot can use directly, just a convenient extra.

I think it would be good to merge. It would be neat if this could be integrated into the Certbot call like:

    --deploy-hook "/etc/letsencrypt/cpanel-dns.py install TARGET_DOMAIN"

and we could do away with the `CPANEL_TARGET_DOMAIN` variable, in that case.

2022-10-03 23:35 UTC, DragoonAethis commented
Oh, I didn't know about deploy hooks - I'll try to get it up and running with that tomorrow.

2022-10-06 18:12 UTC, DragoonAethis commented
Alright, tomorrow is today :D I read that Certbot sets `RENEWED_LINEAGE` to the renewed cert's live dir and calls the hook multiple times for multiple generated certs, so it now pulls the domain name from the certificate's path. This can be overridden from the command line, too. This gets rid of all the new install variables.

2022-10-06 19:28 UTC, alexzorin requested changes
Thanks, this seems to work well. Just a few minor items in this review.

2022-10-06 19:28 UTC, alexzorin commented on README.md
> +You can optionally add `--deploy-hook "/etc/letsencrypt/cpanel-dns.py install` to install the issued certificate on the same CPanel domain as is the certificate's lineage name (in the example above:
```suggestion
You can optionally add `--deploy-hook "/etc/letsencrypt/cpanel-dns.py install"` to install the issued certificate on the same cPanel domain as is the certificate's lineage name (in the example above: `example.com`). You can also use `... install example.com` to specify its name if your cPanel domain is different.
```

2022-10-06 19:28 UTC, alexzorin commented on cpanel-dns.py
> +        print(f"Installing certificate for CPanel domain: {domain}")
```suggestion
        print(f"Installing certificate for cPanel domain: {domain}")
```

2022-10-06 19:28 UTC, alexzorin commented on cpanel-dns.py
> +            domain = cert_live_dir.split('/')[-1]
```suggestion
            domain = os.path.basename(os.path.normpath(cert_live_dir))
```

2022-10-06 19:34 UTC, DragoonAethis commented
All suggestions merged, thanks!

2022-10-06 19:36 UTC, merged